import type {Metadata} from "next";
import "../styles/globals.css";
import {Inter as FontSans} from "next/font/google"
import {cn} from "@/lib/utils";
import React from "react";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn(
            "min-h-screen font-sans antialiased",
            fontSans.variable
        )}>
        {children}
        </body>
        </html>
    );
}
